name: Deploy to Surge

on:
  push:
      branches: [main]

jobs:
  deploy:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to changani.me
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'changani.me'
          project: './'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}